# Generated by Django 2.1.1 on 2018-10-11 14:58

import apps.persona.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.Persona'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(apps.persona.models.default_seccion), to='persona.Seccion'),
        ),
    ]
